version: "3.7"
services:
  back:
    build:
      context: ./
      dockerfile: resources/Dockerfile-back
      args:
        BACK_NR_LICENCE: ${BACK_NR_LICENCE}
    environment:
      NETWORK: ${BACK_NETWORK}
      PORT: ${BACK_PORT}
      BACK_SENTRY_DSN: ${BACK_SENTRY_DSN}
      BACK_WALLET_RPC_HOST: ${BACK_WALLET_RPC_HOST}
      BACK_WALLET_RPC_PORT: ${BACK_WALLET_RPC_PORT}
    ports:
      - ${BACK_HOST_PORT}:${BACK_PORT}
    depends_on:
      - rpc
  front:
    depends_on:
      - back
    build:
      context: ./
      dockerfile: resources/Dockerfile-front
    environment:
      REACT_APP_RPC_URL: ${BACK_RPC_URL}:${BACK_HOST_PORT}/rpc
      REACT_APP_SENTRY_DSN: ${REACT_APP_SENTRY_DSN}
    ports: 
      - ${FRONT_HOST_PORT}:${FRONT_PORT}
  havend:
    image: haven-web-wallet_havend
    build:
      context: ./
      dockerfile: resources/Dockerfile-havend
      args:
        NETWORK: ${BACK_NETWORK}
        DAEMON_RPC_PORT: ${DAEMON_RPC_PORT}
        DAEMON_P2P_PORT: ${DAEMON_P2P_PORT}
        DAEMON_HOST: ${DAEMON_HOST}
        RPC_WALLET_DIR: ${RPC_WALLET_DIR}
        BACK_WALLET_RPC_PORT: ${BACK_WALLET_RPC_PORT}
    volumes:
      - ${DAEMON_BC_PATH}:/root/.haven
    command: ["bash", "/bootstrap-daemon.sh"]
    
  rpc:
    image: haven-web-wallet_havend
    depends_on:
      - havend
    volumes:
      - ${RPC_WALLET_DIR}:/wallet
    environment:
      NETWORK: ${BACK_NETWORK}
    ports:
      - ${BACK_WALLET_RPC_PORT}:${BACK_WALLET_RPC_PORT}
    command: ["bash", "/bootstrap-wallet.sh"]
