version: "3.8"
services:
  web-app:
    build: 
      dockerfile: .docker/node/Dockerfile
      context: ./
    volumes: 
      - type: bind
        source: ./client/
        target: /var/www/
    environment:
      ENV: 2
      REACT_APP_NET_TYPE_ID: 2
      FAST_REFRESH: 0
    command: ['npm','run','start:web']

  havend:
    image: havenprotocolorg/haven-cli:latest
    command: ['havend','--stagenet','--non-interactive','--add-exclusive-node','seed02-stagenet.havenprotocol.org:37750']
    volumes:
      - type: volume
        source: havend
        target: /home/haven/.haven
  haproxy:
    depends_on:
      - havend
      - web-app
    build:
      dockerfile: Dockerfile
      context: .docker/haproxy
    ports:
      - 80:80

volumes:
  havend: