# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI Desktop Vault

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

env:
  REACT_APP_NET_TYPE_ID: 0

jobs:
  desktop-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    
    - name: Install client dependencies
      working-directory: client
      run: |
          npm install

    - name: Audit client dependencies
      working-directory: client
      run: |
          npm audit fix --production

    - name: Client Build for Desktop
      working-directory: client
      env:
        CI: false
      run: |
          npm run build:desktop:ci 

    - name: Copy Build
      working-directory: client
      run: |
          npm run copy-build

    - name: Install backend dependencies
      working-directory: haven-desktop-app
      run: |
          npm install

    - name: Audit backend dependencies
      working-directory: haven-desktop-app
      run: |
          npm audit fix --production

    - name: Build Final App
      run: |
          sh './sh/make.sh'

    - name: Upload Build
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}
        path: haven-desktop-app/out/make/

  web-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    
    - name: Install client dependencies
      working-directory: client
      run: |
          npm install

    - name: Copy wallet core to root folder
      working-directory: client
      run: |
          npm run copy-haven-core

    - name: Audit client dependencies
      working-directory: client
      run: |
          npm audit fix --production

    - name: Client Build for Web
      working-directory: client
      env:
        CI: false
      run: |
          npm run build:web:ci

    - name: Upload web build
      uses: actions/upload-artifact@v2
      with:
        name: web_build
        path: client/build/

