# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI Desktop Vault

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  desktop-build:
    runs-on: ${{ matrix.os }}
    env: 
      REACT_APP_NET_TYPE_ID: ${{matrix.network}}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
        network: [0, 1, 2]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    
    - name: Install client dependencies
      working-directory: client
      run: |
          npm install

    - name: Audit client dependencies
      working-directory: client
      run: |
          npm audit fix --production

    - name: Client Build for Desktop
      working-directory: client
      env:
        CI: false
      run: |
          npm run build:desktop:ci 

    - name: Copy Build
      working-directory: client
      run: |
          npm run copy-build

    - name: Install backend dependencies
      working-directory: haven-desktop-app
      run: |
          npm install

    - name: Install latest wallet core
      working-directory: haven-desktop-app
      run: |
          npm install haven-wallet-core@latest --save

    - name: Audit backend dependencies
      working-directory: haven-desktop-app
      run: |
          npm audit fix --production

    - if: matrix.os == 'ubuntu-latest'
      run: |
          sudo apt-get install flatpak flatpak-builder elfutils

    - name: Build Final App
      run: |
          sh './sh/make.sh'

    - name: Upload Build
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-${{ matrix.network }}
        path: haven-desktop-app/out/make/