# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI Desktop Vault

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  REACT_APP_NET_TYPE_ID: 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    
    - name: Install client dependencies
      working-directory: client
      run: |
          npm install

    - name: Audit client dependencies
      working-directory: client
      run: |
          npm audit fix --audit-level=moderate

    - name: Client Build for Desktop
      working-directory: client
      env:
        CI: false
      run: |
          npm run build:web:ci 

    - name: Upload web build
      uses: actions/upload-artifact@v2
      with:
        name: web_build
        path: client/build/

